services:
  backend:
    image: ghcr.io/thanh-hoang-codeleap/ai-exam-review/ai-exam-reviewer-backend:latest
    container_name: ai-exam-reviewer-backend
    ports:
      - "8000:8000"

  frontend:
    image: ghcr.io/thanh-hoang-codeleap/ai-exam-review/ai-exam-reviewer-frontend:latest
    container_name: ai-exam-reviewer-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
